[package]
name = "pixel-soccer"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = "0.1.53"
atomic_float = "0.1.0"
clap = { version = "3.1.12", features = ["derive"] }
image = "0.24.2"
lazy_static = "1.4.0"
regex = "1.5.5"
tokio = { version = "1.18.0", features = ["full"] }
